greenery:
  outputs:
    dbt_w3n:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: postgres #"{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_w3n

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    prod_bigquery:
      type: bigquery
      method: service-account
      project: dataengineercafe
      dataset: greenery
      threads: 1
      keyfile: "{{ env_var('DBT_ENV_SECRET_GCP_KEYFILE_PATH') }}"
      location: asia-southeast1

  target: dbt_w3n
